name: Branch Protection

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          test
          chore
        scopes: |
          core
          api
          infrastructure
          tests
          ci
        requireScope: false

  enforce-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Start MongoDB using docker compose
      run: |
        cd database
        docker compose up -d mongodb
        echo "Waiting for MongoDB to be ready..."
        sleep 15
        
        # Wait for MongoDB to be fully ready
        timeout 60 bash -c 'until docker exec minisocial-mongodb mongosh --eval "db.adminCommand(\"ping\")" > /dev/null 2>&1; do sleep 2; done'
        echo "MongoDB is ready!"
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Run tests with coverage
      run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory ./coverage
      env:
        MongoDb__ConnectionString: "mongodb://minisocial_user:minisocial_password@localhost:27017/minisocial?authSource=minisocial"
    
    - name: Stop MongoDB
      if: always()
      run: |
        cd database
        docker compose down
    
    - name: Check test coverage
      run: |
        # This is a placeholder - you would typically use a tool like ReportGenerator
        # to parse coverage and enforce minimum thresholds
        echo "Checking test coverage..."
        find ./coverage -name "*.xml" | head -1

  security-scan:
    runs-on: ubuntu-latest
    needs: enforce-tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Security scan
      run: dotnet list package --vulnerable --include-transitive
